#!/bin/bash
hostname=katana
username=null
password=N3pster128megabyte*
sysadmin=true
luksdevs=crypto_root
lukstate=true
diskboot=/dev/nvme0n1p1
diskroot=/dev/nvme0n1p4
timeregs=Asia
timecity=Jakarta
locales1="en_US.UTF-8 UTF-8"
locales2="en_US ISO-8859-1"