#!/bin/bash


## profile option menu 
## return value of this function is @int profile_option 
function bb_pre_dial_prof_menu() {

    menus=$( ls $base_path/env/profile/ )

    echo ' Installation profile : '
    echo ' [1] Example profile ';
    if [[ $( ls $base_path/env/profile | wc -l ) -gt 0 ]];then
        for i in "${!menus[@]}"; do
            number=$(( $i + 2 ))
            echo '' "[$number] ${menus[$i]}"
        done
    fi
    read -p "Choose profile by type their number : " profile_option
}


